# Makefile — Confidential Payments Rollup on Stellar
# Plans: plans/s1/01-scaffold-and-pin.md
#
# Each target begins with prereq checks and exits loudly if requirements are
# not met (CONTEXT.md D5 / AC5.1: reproducible from a clean clone).
#
# DOCKER NOTE (AC5.2): The STARK→Groth16 wrap requires Docker.
#   On ARM (Apple Silicon) the wrap runs inside a risc0/groth16-prover image.
#   Without Docker the host falls back to dev mode (fake receipt) which CANNOT
#   be verified on-chain — violates the "ELIMINATORIA" rule.

# ── Config ────────────────────────────────────────────────────────────────────
GOLDEN_DIR  := golden
# s1/04: the host `prove` subcommand loads the golden N=2 inputs and writes the
# receipt artifacts (seal.hex / image_id.hex / journal.bin) under out/receipt/.
GOLDEN_FILE := $(GOLDEN_DIR)/n2_inputs.json
RECEIPT_DIR := out/receipt

.PHONY: prove bench demo-dryrun check-docker check-golden _prereq-prove _prereq-bench _prereq-demo clean help

# ── Help (default) ────────────────────────────────────────────────────────────
help:
	@echo ""
	@echo "Confidential Payments Rollup — Makefile targets"
	@echo "  make prove        — prove the rollup guest (requires Docker + golden inputs)"
	@echo "  make bench        — benchmark proving time for N=16, N=32"
	@echo "  make demo-dryrun  — end-to-end dry run against testnet (no live proving)"
	@echo ""
	@echo "Prerequisites:"
	@echo "  Docker running with internet access (STARK→Groth16 wrap on ARM)"
	@echo "  golden/inputs.json present (generated by s1/02 cross-check)"
	@echo ""

# ── Docker check ──────────────────────────────────────────────────────────────
check-docker:
	@echo "[prereq] checking Docker..."
	@docker info > /dev/null 2>&1 || \
		(echo "" && \
		 echo "ERROR: Docker is not running." && \
		 echo "" && \
		 echo "  The STARK→Groth16 wrap (AC5.1, AC5.2) requires Docker." && \
		 echo "  On ARM (Apple Silicon) the wrap runs inside risc0/groth16-prover." && \
		 echo "  Without Docker the receipt cannot be verified on-chain." && \
		 echo "" && \
		 echo "  Start Docker Desktop and retry." && \
		 echo "" && \
		 exit 1)
	@echo "[prereq] Docker OK"

# ── Golden inputs check ───────────────────────────────────────────────────────
check-golden:
	@echo "[prereq] checking golden inputs..."
	@test -f "$(GOLDEN_FILE)" || \
		(echo "" && \
		 echo "ERROR: Golden inputs not found at $(GOLDEN_FILE)." && \
		 echo "" && \
		 echo "  The golden N=2 inputs are frozen PoC-derived vectors checked into" && \
		 echo "  the repo (golden/n2_inputs.json), produced by tasks s1/02-s1/03." && \
		 echo "" && \
		 exit 1)
	@echo "[prereq] golden inputs OK: $(GOLDEN_FILE)"

# ── prove ─────────────────────────────────────────────────────────────────────
# Prereqs: Docker running + golden inputs present.
# Runs the host `prove` subcommand: loads golden/n2_inputs.json, proves the guest
# to Groth16/BN254 (STARK->SNARK wrap in the risc0 groth16-prover container),
# verifies receipt.verify(GUEST_ID) locally, then serializes the artifacts under
# $(RECEIPT_DIR): seal.hex (encode_seal), image_id.hex (32B), journal.bin.
# RISC0_DEV_MODE=0 is forced so the wrap is a REAL Groth16 proof, never a fake.
_prereq-prove: check-docker check-golden

prove: _prereq-prove
	@echo ""
	@echo "==> make prove: generating Groth16 receipt for the rollup batch"
	@echo "    (RISC Zero 3.0.5, Groth16/BN254, Docker wrap)"
	@echo ""
	RISC0_DEV_MODE=0 cargo run --release -p host -- prove
	@echo ""
	@echo "==> receipt artifacts written to $(RECEIPT_DIR)/"
	@echo ""

# ── bench ─────────────────────────────────────────────────────────────────────
# Prereqs: Docker running (proving is real).
# Measures proving time for N=16 and N=32 (AC6.2 two-axis benchmark setup).
# Full benchmark implementation is in s3/01.
_prereq-bench: check-docker

bench: _prereq-bench
	@echo ""
	@echo "==> make bench: proving-time benchmark (N=16, N=32)"
	@echo "    (full two-axis benchmark implemented in s3/01)"
	@echo ""
	@test -d bench || \
		(echo "ERROR: bench/ directory not found." && \
		 echo "  Benchmark harness is implemented in s3/01." && \
		 exit 1)
	RISC0_DEV_MODE=0 cargo run --release -p bench -- \
		--n-values 16,32
	@echo ""

# ── demo-dryrun ───────────────────────────────────────────────────────────────
# Prereqs: golden inputs (uses pre-generated receipt, no Docker needed).
# Simulates the full settle_batch call against testnet without live proving.
# The receipt artifacts must already exist under $(RECEIPT_DIR) (`make prove`).
# NOTE: the submit/sequencer logic is implemented in s2/05; this is a stub gate.
_prereq-demo: check-golden
	@echo "[prereq] checking pre-generated receipt..."
	@test -s "$(RECEIPT_DIR)/seal.hex" || \
		(echo "" && \
		 echo "ERROR: Pre-generated receipt not found under $(RECEIPT_DIR)/." && \
		 echo "" && \
		 echo "  Run 'make prove' first to generate the Groth16 receipt." && \
		 echo "  (The demo-dryrun submits a pre-generated receipt, not a live proof.)" && \
		 echo "" && \
		 exit 1)
	@echo "[prereq] receipt OK: $(RECEIPT_DIR)/"

demo-dryrun: _prereq-demo
	@echo ""
	@echo "==> make demo-dryrun: settle_batch against testnet (dry run)"
	@echo "    (sequencer + submit logic implemented in s2/05)"
	@echo ""
	@echo "    receipt:  $(RECEIPT_DIR)/{seal.hex,image_id.hex,journal.bin}"
	@echo "    network:  testnet"
	@echo ""
	@echo "    (s2/05 wires the testnet submit; nothing to run yet)"
	@echo ""

# ── clean ─────────────────────────────────────────────────────────────────────
clean:
	cargo clean
	rm -rf $(RECEIPT_DIR)
