//! BLOQUEANTE cross-check (CONTEXT.md D1 / AC1.2, AC1.3).
//!
//! Loads the frozen golden vectors that were generated by the PoC's OWN Rust
//! (`stellar-private-payments` `prover::crypto` + `circuits::core::merkle`) and
//! asserts, BYTE-FOR-BYTE (32-byte little-endian), that zk-core reproduces:
//!   - the note commitment,
//!   - the nullifier (two-step: signature then nullify),
//!   - the Merkle root recomputed from the leaf + sibling path,
//!   - (defense-in-depth) the derived public key and the signature.
//!
//! If a single byte differs, this test fails and s1 stops — nothing downstream
//! integrates until commitment + nullifier + root are byte-identical to the PoC.

use zk_core::merkle;
use zk_core::note::{self, Note};
use zk_core::poseidon2::Fr;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct GoldenFile {
    #[allow(dead_code)]
    description: String,
    tree_depth: usize,
    n_leaves: usize,
    zero_leaf_le: String,
    merkle_root_le: String,
    vectors: Vec<GoldenVector>,
}

#[derive(Debug, Deserialize)]
struct GoldenVector {
    label: String,
    amount: u64,
    amount_le: String,
    priv_key_le: String,
    blinding_le: String,
    leaf_index: u64,
    path_indices: u64,
    pubkey_le: String,
    commitment_le: String,
    signature_le: String,
    nullifier_le: String,
    path_elements_le: Vec<String>,
}

/// 0x-prefixed little-endian hex -> 32-byte array.
fn le32(s: &str) -> [u8; 32] {
    let s = s.strip_prefix("0x").unwrap_or(s);
    let v = hex::decode(s).expect("valid hex");
    assert_eq!(v.len(), 32, "expected 32-byte LE scalar, got {}", v.len());
    let mut out = [0u8; 32];
    out.copy_from_slice(&v);
    out
}

fn fr_le(s: &str) -> Fr {
    note::fr_from_le_bytes(&le32(s))
}

fn load_golden() -> GoldenFile {
    let raw = include_str!("../../../golden/poc_vectors.json");
    serde_json::from_str(raw).expect("golden/poc_vectors.json parses")
}

#[test]
fn crosscheck_commitment_nullifier_root_byte_identical() {
    let golden = load_golden();
    assert!(!golden.vectors.is_empty(), "no golden vectors loaded");
    println!(
        "loaded {} golden vectors (depth {}, {} leaves) from the PoC",
        golden.vectors.len(),
        golden.tree_depth,
        golden.n_leaves
    );

    // The zero leaf the PoC used to pad the tree.
    let zero_leaf = fr_le(&golden.zero_leaf_le);
    let expected_root = le32(&golden.merkle_root_le);

    let mut all_ok = true;

    for v in &golden.vectors {
        let amount = fr_le(&v.amount_le);
        // Sanity: the u64 amount and its LE field encoding agree.
        assert_eq!(amount, Fr::from(v.amount), "[{}] amount encoding", v.label);

        let priv_key = fr_le(&v.priv_key_le);
        let blinding = fr_le(&v.blinding_le);

        let n = Note {
            amount,
            priv_key,
            blinding,
            leaf_index: v.leaf_index,
        };

        // --- public key (defense-in-depth) ---
        let pubkey = note::public_key(priv_key);
        let pubkey_bytes = note::fr_to_le_bytes(&pubkey);
        let exp_pubkey = le32(&v.pubkey_le);
        let pubkey_ok = pubkey_bytes == exp_pubkey;

        // --- commitment ---
        let commitment = note::commitment(&n);
        let commitment_bytes = note::fr_to_le_bytes(&commitment);
        let exp_commitment = le32(&v.commitment_le);
        let commitment_ok = commitment_bytes == exp_commitment;

        // --- signature (defense-in-depth) ---
        let signature = note::signature(&n, commitment);
        let signature_bytes = note::fr_to_le_bytes(&signature);
        let exp_signature = le32(&v.signature_le);
        let signature_ok = signature_bytes == exp_signature;

        // --- nullifier (two-step: sign then nullify) ---
        let nullifier = note::nullifier(&n, priv_key);
        let nullifier_bytes = note::fr_to_le_bytes(&nullifier);
        let exp_nullifier = le32(&v.nullifier_le);
        let nullifier_ok = nullifier_bytes == exp_nullifier;

        // --- merkle root from leaf + sibling path ---
        let path: std::vec::Vec<Fr> = v.path_elements_le.iter().map(|h| fr_le(h)).collect();
        // index bits used by root_from_path == packed path_indices == leaf_index here.
        assert_eq!(v.path_indices, v.leaf_index, "[{}] packed indices", v.label);
        let root = merkle::root_from_path(commitment, &path, v.path_indices);
        let root_bytes = note::fr_to_le_bytes(&root);
        let root_ok = root_bytes == expected_root;

        println!(
            "  [{}] pubkey={} commitment={} signature={} nullifier={} root={}",
            v.label,
            yn(pubkey_ok),
            yn(commitment_ok),
            yn(signature_ok),
            yn(nullifier_ok),
            yn(root_ok),
        );

        if !pubkey_ok {
            eprintln!(
                "    pubkey     got {} != exp {}",
                hx(&pubkey_bytes),
                hx(&exp_pubkey)
            );
        }
        if !commitment_ok {
            eprintln!(
                "    commitment got {} != exp {}",
                hx(&commitment_bytes),
                hx(&exp_commitment)
            );
        }
        if !signature_ok {
            eprintln!(
                "    signature  got {} != exp {}",
                hx(&signature_bytes),
                hx(&exp_signature)
            );
        }
        if !nullifier_ok {
            eprintln!(
                "    nullifier  got {} != exp {}",
                hx(&nullifier_bytes),
                hx(&exp_nullifier)
            );
        }
        if !root_ok {
            eprintln!(
                "    root       got {} != exp {}",
                hx(&root_bytes),
                hx(&expected_root)
            );
        }

        // Hard per-field byte-for-byte assertions (the definition of done).
        assert_eq!(
            commitment_bytes, exp_commitment,
            "[{}] commitment NOT byte-identical",
            v.label
        );
        assert_eq!(
            nullifier_bytes, exp_nullifier,
            "[{}] nullifier NOT byte-identical",
            v.label
        );
        assert_eq!(
            root_bytes, expected_root,
            "[{}] merkle root NOT byte-identical",
            v.label
        );
        assert_eq!(
            pubkey_bytes, exp_pubkey,
            "[{}] pubkey NOT byte-identical",
            v.label
        );
        assert_eq!(
            signature_bytes, exp_signature,
            "[{}] signature NOT byte-identical",
            v.label
        );

        all_ok &= pubkey_ok && commitment_ok && signature_ok && nullifier_ok && root_ok;

        // keep the zero leaf referenced so the import/value is exercised
        let _ = zero_leaf;
    }

    assert!(
        all_ok,
        "one or more golden vectors did not reproduce byte-identical"
    );
    println!(
        "ALL {} vectors reproduce byte-identical (commitment + nullifier + root)",
        golden.vectors.len()
    );
}

fn yn(b: bool) -> &'static str {
    if b {
        "OK"
    } else {
        "MISMATCH"
    }
}

fn hx(b: &[u8]) -> String {
    let mut s = String::from("0x");
    for x in b {
        s.push_str(&format!("{:02x}", x));
    }
    s
}
