//! BLOQUEANTE cross-check — EDGE-INPUT scalars (s1/02b security follow-up).
//!
//! Companion to `crosscheck_poc.rs`. The 4 proven vectors all use field inputs
//! whose LE high byte is 0 (always `< r`), so `from_le_bytes_mod_order` never
//! reduces — the **modular-reduction path** inside commitment / signature /
//! nullifier was untested. These edge vectors were generated by the PoC's OWN
//! Rust (`stellar-private-payments` `prover::crypto`, module
//! `golden_s1_02_edge.rs`) with edge-input scalars (`r-1`, values `>= r` that
//! force reduction, and a fixed-seed random draw), and frozen into
//! `golden/poc_vectors_edge.json`.
//!
//! This test asserts, BYTE-FOR-BYTE (32-byte little-endian), that zk-core
//! reproduces the PoC's pubkey, commitment, signature and nullifier for those
//! edge inputs.
//!
//! CRITICAL: the edge INPUT scalars (amount / priv_key / blinding) may be
//! `>= r`. They MUST be parsed with `from_le_bytes_mod_order` (mod-order
//! reduction) — exactly what the PoC's `bytes_to_scalar` does — NOT a strict
//! canonical deserialize, which would reject them. `note::fr_from_le_bytes`
//! (used by `fr_le` below) is `Fr::from_le_bytes_mod_order`, so it matches.
//! All OUTPUTS are canonical (`< r`) and are compared byte-exact.
//!
//! If a single byte differs, this test fails and s1 stops — a divergence here
//! is the project's cryptographic foundation cracking, and is the exact signal
//! this follow-up hunts for. The test never adjusts itself to go green.

use zk_core::note::{self, Note};
use zk_core::poseidon2::Fr;

use ark_ff::{BigInteger, PrimeField};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct EdgeFile {
    #[allow(dead_code)]
    description: String,
    modulus_le: String,
    vectors: Vec<EdgeVector>,
}

#[derive(Debug, Deserialize)]
struct EdgeVector {
    label: String,
    #[allow(dead_code)]
    note: String,
    amount_le: String,
    priv_key_le: String,
    blinding_le: String,
    leaf_index: u64,
    path_indices: u64,
    pubkey_le: String,
    commitment_le: String,
    signature_le: String,
    nullifier_le: String,
}

/// 0x-prefixed little-endian hex -> 32-byte array.
fn le32(s: &str) -> [u8; 32] {
    let s = s.strip_prefix("0x").unwrap_or(s);
    let v = hex::decode(s).expect("valid hex");
    assert_eq!(v.len(), 32, "expected 32-byte LE scalar, got {}", v.len());
    let mut out = [0u8; 32];
    out.copy_from_slice(&v);
    out
}

/// Parse an INPUT scalar from 0x LE hex via mod-order reduction
/// (`from_le_bytes_mod_order`, matching the PoC's `bytes_to_scalar`). This is
/// the load-bearing detail for edge inputs `>= r`.
fn fr_le(s: &str) -> Fr {
    note::fr_from_le_bytes(&le32(s))
}

/// Compare two 32-byte LE arrays as unsigned little-endian integers.
/// Returns true iff `a >= b`. Used to PROVE the over-modulus inputs are really
/// `>= r` (i.e. the reduction path is genuinely exercised).
fn ge_le(a: &[u8; 32], b: &[u8; 32]) -> bool {
    for i in (0..32).rev() {
        if a[i] != b[i] {
            return a[i] > b[i];
        }
    }
    true // equal
}

fn load_edge() -> EdgeFile {
    let raw = include_str!("../../../golden/poc_vectors_edge.json");
    serde_json::from_str(raw).expect("golden/poc_vectors_edge.json parses")
}

#[test]
fn crosscheck_edge_commitment_nullifier_byte_identical() {
    let edge = load_edge();
    assert!(!edge.vectors.is_empty(), "no edge vectors loaded");
    let modulus = le32(&edge.modulus_le);
    println!(
        "loaded {} EDGE golden vectors from the PoC (modulus r = {} LE)",
        edge.vectors.len(),
        hx(&modulus),
    );

    // Provenance/intent guard: at least one vector MUST carry a raw input >= r,
    // otherwise these "edge" vectors would not actually exercise the reduction
    // path and the follow-up would be vacuous.
    let mut saw_reduction_input = false;

    let mut all_ok = true;

    for v in &edge.vectors {
        let amount_raw = le32(&v.amount_le);
        let priv_raw = le32(&v.priv_key_le);
        let blind_raw = le32(&v.blinding_le);

        // Is any raw input >= r (will be reduced by from_le_bytes_mod_order)?
        let reduces = ge_le(&amount_raw, &modulus)
            || ge_le(&priv_raw, &modulus)
            || ge_le(&blind_raw, &modulus);
        saw_reduction_input |= reduces;

        // Parse inputs with mod-order reduction (matches the PoC). For raw
        // inputs >= r this is where the reduction actually happens.
        let amount = fr_le(&v.amount_le);
        let priv_key = fr_le(&v.priv_key_le);
        let blinding = fr_le(&v.blinding_le);

        assert_eq!(
            v.path_indices, v.leaf_index,
            "[{}] packed indices == leaf index",
            v.label
        );

        let n = Note {
            amount,
            priv_key,
            blinding,
            leaf_index: v.leaf_index,
        };

        // --- public key ---
        let pubkey = note::public_key(priv_key);
        let pubkey_bytes = note::fr_to_le_bytes(&pubkey);
        let exp_pubkey = le32(&v.pubkey_le);
        let pubkey_ok = pubkey_bytes == exp_pubkey;

        // --- commitment ---
        let commitment = note::commitment(&n);
        let commitment_bytes = note::fr_to_le_bytes(&commitment);
        let exp_commitment = le32(&v.commitment_le);
        let commitment_ok = commitment_bytes == exp_commitment;

        // --- signature ---
        let signature = note::signature(&n, commitment);
        let signature_bytes = note::fr_to_le_bytes(&signature);
        let exp_signature = le32(&v.signature_le);
        let signature_ok = signature_bytes == exp_signature;

        // --- nullifier (two-step: sign then nullify) ---
        let nullifier = note::nullifier(&n, priv_key);
        let nullifier_bytes = note::fr_to_le_bytes(&nullifier);
        let exp_nullifier = le32(&v.nullifier_le);
        let nullifier_ok = nullifier_bytes == exp_nullifier;

        // Every OUTPUT must be canonical (< r). (Sanity on the golden + our port.)
        assert!(
            !ge_le(&commitment_bytes, &modulus),
            "[{}] commitment output must be < r (canonical)",
            v.label
        );
        assert!(
            !ge_le(&nullifier_bytes, &modulus),
            "[{}] nullifier output must be < r (canonical)",
            v.label
        );

        println!(
            "  [{}] reduces_input={} pubkey={} commitment={} signature={} nullifier={}",
            v.label,
            yn_bool(reduces),
            yn(pubkey_ok),
            yn(commitment_ok),
            yn(signature_ok),
            yn(nullifier_ok),
        );

        if !pubkey_ok {
            eprintln!(
                "    DIVERGENCE pubkey     got {} != exp {}",
                hx(&pubkey_bytes),
                hx(&exp_pubkey)
            );
        }
        if !commitment_ok {
            eprintln!(
                "    DIVERGENCE commitment got {} != exp {}",
                hx(&commitment_bytes),
                hx(&exp_commitment)
            );
        }
        if !signature_ok {
            eprintln!(
                "    DIVERGENCE signature  got {} != exp {}",
                hx(&signature_bytes),
                hx(&exp_signature)
            );
        }
        if !nullifier_ok {
            eprintln!(
                "    DIVERGENCE nullifier  got {} != exp {}",
                hx(&nullifier_bytes),
                hx(&exp_nullifier)
            );
        }

        // Hard per-field byte-for-byte assertions (the definition of done).
        // NOTE: we do NOT relax these on mismatch — a divergence must surface.
        assert_eq!(
            commitment_bytes, exp_commitment,
            "[{}] commitment NOT byte-identical (PoC vs zk-core)",
            v.label
        );
        assert_eq!(
            nullifier_bytes, exp_nullifier,
            "[{}] nullifier NOT byte-identical (PoC vs zk-core)",
            v.label
        );
        assert_eq!(
            pubkey_bytes, exp_pubkey,
            "[{}] pubkey NOT byte-identical (PoC vs zk-core)",
            v.label
        );
        assert_eq!(
            signature_bytes, exp_signature,
            "[{}] signature NOT byte-identical (PoC vs zk-core)",
            v.label
        );

        all_ok &= pubkey_ok && commitment_ok && signature_ok && nullifier_ok;
    }

    assert!(
        saw_reduction_input,
        "edge vectors did not contain any input >= r: the reduction path was NOT exercised \
         (these vectors would be vacuous)"
    );
    assert!(
        all_ok,
        "one or more EDGE golden vectors did not reproduce byte-identical — DIVERGENCE"
    );
    println!(
        "ALL {} EDGE vectors reproduce byte-identical (pubkey + commitment + signature + nullifier); \
         reduction path exercised.",
        edge.vectors.len()
    );
}

/// Independent assertion that `fr_from_le_bytes` performs mod-order reduction:
/// the raw modulus `r` (LE) must decode to 0, and `r + k` must decode to `k`.
/// If this ever stops holding, the edge cross-check above would be testing the
/// wrong thing — so we pin it explicitly.
#[test]
fn fr_from_le_bytes_reduces_mod_order() {
    let edge = load_edge();
    let r = le32(&edge.modulus_le);

    // r mod r == 0
    let zero = note::fr_from_le_bytes(&r);
    assert_eq!(zero, Fr::from(0u64), "r must reduce to 0");

    // (r + 7) mod r == 7  -> add 7 to the LE modulus with carry.
    let mut r_plus_7 = r;
    let mut carry = 7u16;
    let mut i = 0;
    while carry != 0 && i < 32 {
        let s = r_plus_7[i] as u16 + (carry & 0xff);
        r_plus_7[i] = (s & 0xff) as u8;
        carry = (s >> 8) + (carry >> 8);
        i += 1;
    }
    let seven = note::fr_from_le_bytes(&r_plus_7);
    assert_eq!(seven, Fr::from(7u64), "(r + 7) must reduce to 7");

    // And a canonical sanity: encoding 7 round-trips to the same LE byte 0x07.
    let mut le_seven = [0u8; 32];
    le_seven[0] = 7;
    assert_eq!(
        note::fr_to_le_bytes(&seven),
        le_seven,
        "7 encodes to 0x07.. LE"
    );

    // Keep the BigInteger/PrimeField imports load-bearing (used via Fr ops).
    let _ = Fr::from(0u64).into_bigint().to_bytes_le();
}

fn yn(b: bool) -> &'static str {
    if b {
        "OK"
    } else {
        "MISMATCH"
    }
}

fn yn_bool(b: bool) -> &'static str {
    if b {
        "yes"
    } else {
        "no"
    }
}

fn hx(b: &[u8]) -> String {
    let mut s = String::from("0x");
    for x in b {
        s.push_str(&format!("{:02x}", x));
    }
    s
}
