//! Exposes the compiled guest ELF bytes and image ID.
//!
//! The constants are generated by `risc0-build` during `cargo build`.
//! In dev mode (RISC0_DEV_MODE=1) risc0-zkvm substitutes a fake receipt;
//! in production the real Groth16 receipt is required.

// Include generated constants from risc0-build.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
